name: Build and Push Frontend

on:
  push:
    branches: ["main"]

env:
  IMAGE_TAG: "1.0.0"

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Filter frontend changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'frontend/**'
              - 'package*.json'
              - 'next.config.js'
              - 'public/**'

  build-and-push:
    needs: filter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Log changes
        run: echo "Frontend changes? ${{ needs.filter.outputs.frontend }}"

      - name: Log in to Docker Hub
        if: ${{ needs.filter.outputs.frontend == 'true' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend Docker image
        if: ${{ needs.filter.outputs.frontend == 'true' }}
        run: |
          docker build -f frontend/Dockerfile \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/interview-system-frontend:${{ env.IMAGE_TAG }} frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/interview-system-frontend:${{ env.IMAGE_TAG }}
